### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by rupipal** [russellallen/self#119]
Hi,
Could you share an installer fro Windows 7?

Could you list steps to build on Windows?

Rupinder

**Comment by doublec** [comment]
Self unfortunately does not currently build on Windows. Having someone work on or contribute a Windows port would be marvellous.

**Comment by rupipal** [comment]
Ok. Thanks. I guess I'll try it on ubuntu in virtual box. Hope someone contributes Windows port soon.
