### ISSUE TITLE
'string capitalizeAll' doesn't work for numbers

### ISSUE THREAD

**Issue by doublec** [russellallen/self#124]
If I try to capitalize a string with numbers, the numbers are changed to unprintable characters:

    'abcd1234defg' capitalizeAll
    'ABCD????DEFG'

Tested with github master branch.

**Comment by russellallen** [comment]
Lol. Well the simplest fix is to change:

`capitalizeAll = (copyMutable mapBy: [|:c| c isCapitalized ifTrue: c False: [(c asByte + capitalizationDifference) asCharacter]])`

to 

`copyMutable mapBy: [|:c| (c isLetter not || c isCapitalized) ifTrue: c False: [(c asByte + capitalizationDifference) asCharacter]]`

unless you have a better idea...

**Comment by davidungar** [comment]
Yes, that's an amusing bug!

- David

**Comment by doublec** [comment]
Looks good to me!

**Comment by russellallen** [comment]
Fixed - Commit 93b24da on dev branch
