### ISSUE TITLE
Windows prebuilt binary / installer on site

### ISSUE THREAD

**Issue by ponyatov** [russellallen/self#125]
Is there Windows prebuilt binary to look what is this thing look like?

Can't build using CMake: no MinGW support, Visual C only 8-(

**Comment by ponyatov** [comment]
Maybe Self has a metamodel in Smalltalk or deep description of its VM and core internals let me port it to say CogVM, JVM or JS WebAssembly (the best variant)?

**Comment by russellallen** [comment]
Not planned
