### ISSUE TITLE
Linux pre-built: fails to start gui on ubuntu18.04.2  x86-64

### ISSUE THREAD

**Issue by stacksmith** [russellallen/self#127]
1) unknown font: verdana.  I don't think any Linux includes a Microsoft font.  I installed it, but the complaint continued.  I am not sure how to fix this.
2) The documentation talks about 'clean.self' image... There is no such thing in the distribution - I am assuming that core.snap is it...  I was trying morphic and kitchensink for 1)
3) ia32-libs are not normally installed anymore; I think that the following fixes it.  This should be mentioned somewhere...
dpkg --add-architecture i386 
apt update
apt install libc6:i386 
apt install ia32-libs
apt install libxrender1:i386 libxtst6:i386 libxi6:i386
apt install libncurses:i386

**Comment by stacksmith** [comment]
Installed MS TrueType fonts with sudo apt install ttf-mscorefonts-installer - same deal, unknown font: verdana.  I am at a loss

**Comment by russellallen** [comment]
The font is just a warning and shouldn't prevent startup. Installing the TrueType fonts won't work because Self is looking for client side fonts (aka original X fonts).

Can you paste in what your terminal is showing? ie what do you type and what response is given?

**Comment by stacksmith** [comment]
```
stack@green:~/Documents/Self/Self-Release-2017.1$ ./Self -s morphic.snap
for I386:  LogVMMessages = true
for I386:  PrintScriptName  = true
for I386:  Inline = true
for I386:  SICDeferUncommonBranches = false (not implemented)
for I386:  SICReplaceOnStack = false (not implemented)
for I386:  SaveOutgoingArgumentsOfPatchedFrames = true

	Welcome to the Self system!  (2017.1/2)


Copyright 1992-2016 AUTHORS.
See the legal/LICENSE file for license information and legal/AUTHORS for authors.

Type _Credits for full credits.

[Tue May 07 15:56:10 2019] info -- Scheduler started (according to snapshotAction schedulerInitial)
"Self 1" [Tue May 07 15:56:10 2019] info -- Adjusting VM for better UI2 performance:  _MaxPICSize: 25
unknown font: verdana
```

**Comment by doublec** [comment]
At the Self prompt you have above, enter "desktop open" and the GUI should run.

**Comment by stacksmith** [comment]
I am a fool - the gui is up - got buried under other windows.  I was expecting something to come to the top, and the missing font message thew me.
  Sorry!

**Comment by russellallen** [comment]
No worries - glad it's working

**Comment by stacksmith** [comment]
I found this deep inside....https://github.com/russellallen/self/blob/master/release/notes.txt
Since this lists the required i386 libraries for running on modern Ubuntu distros - perhaps you could put it into the top readme...
