### ISSUE TITLE
Java port (and full implementation tutorial to save the language)

### ISSUE THREAD

**Issue by ponyatov** [russellallen/self#129]
Are any attempts were made to make some (maybe very slow) implementation over JVM?

The Self language looks died, but maybe somebody knows enough on VM internals can write a tutorial on implementing very light Self-like system from scratch and step by step (in Python or Java)?

The problem is not the lack of reference implementation support (which need a huge amount a work factically), but promote the language model ideas among programmers in mainstream languages. They can be interested in very easy to understand and implement a very light VM to be used in other commercial and hobby applications as an embeddable script engine.

**Comment by Bystroushaak** [comment]
> Are any attempts were made to make some (maybe very slow) implementation over JVM?

There were some in the history, but I think that none was really successfully finished.

One new project, which I managed to somewhow get intermingled into is

* https://github.com/JaroslavTulach/SelfGraal

It is a implementation of Self for the GraalVM, but it is in very early stage. On the other hand, if this ever get finished, it will offer great speed (ahead of time compiled to machine code) and language interop (you can call java / python / ruby / JS / C from Self code and vice versa).

> The Self language looks died, but maybe somebody knows enough on VM internals can write a tutorial on implementing very light Self-like system from scratch and step by step (in Python or Java)?

I am working exactly on this. You can find my language here:

* https://github.com/Bystroushaak/tinySelf

It is written in the RPython, restricted dialog of python, which is then compiled to C and can also add JIT for much faster speed. It is not exact implementation of Self, but rather somehow loosely inspired.

I have written several episodes of the tutorial about building the language, but right now, it is only in Czech language. I am slowly working on translation to English.

* https://www.notion.so/Jak-se-p-e-programovac-jazyk-3123f4f91327420bbb2fc1a8a6a3e434

Sadly, the blogging platform I am using doesn't allow you to translate the blog by using services like google translate, but I've published the blogs also on abclinuxu:

* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F2%2Fjak-se-pise-programovaci-jazyk-1-motivace
* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F2%2Fjak-se-pise-programovaci-jazyk-2-lexer
* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F2%2Fjak-se-pise-programovaci-jazyk-3-parser-a-ast
* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F2%2Fjak-se-pise-programovaci-jazyk-3.5-rpython
* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F3%2Fjak-se-pise-programovaci-jazyk-4-objektovy-layout
* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F4%2Fjak-se-pise-programovaci-jazyk-5-bajtkod-a-literaly
* https://translate.google.com/translate?sl=cs&tl=en&u=https%3A%2F%2Fwww.abclinuxu.cz%2Fblog%2Fbystroushaak%2F2019%2F5%2Fjak-se-pise-programovaci-jazyk-6-kompilator-ast-do-bytecode

**Comment by russellallen** [comment]
Closed as not planned
