### ISSUE TITLE
Doesn't run on macOS Catalina 64 bit

### ISSUE THREAD

**Issue by sfcgeorge** [russellallen/self#130]
I suspect Self wasn't compiled with 64 bit only support because it doesn't do much on macOS Catalina. 

The "Self Control" (oh I just got the pun) GUI runs, but selecting a snapshot does nothing / flickers in "Running worlds" for a second. So the GUI is fine but something deeper isn't happening.

Running `Self` on the command line produces this weird message 

```
/usr/local/bin/self: line 2: /Applications/Self Control.app/Contents/Resources/Self.app/Contents/MacOS/Self: Bad CPU type in executable
```

Which I think might mean it was compiled 32 bit only since Catalina is 64 bit only.

**Comment by doublec** [comment]
Yes, Self is currently 32 bit only. The VM needs to be ported to 64 bit and a 64 bit JIT compiler implemented.

**Comment by russellallen** [comment]
This isn't going to happen any time soon - closing now.
