### ISSUE TITLE
Modernize memory allocation of spaces

### ISSUE THREAD

**Issue by sin-ack** [russellallen/self#157]
Apparently, back in the days of yore, the "portable" way to allocate some empty pages for yourself was to `mmap("/dev/zero")`:

https://github.com/russellallen/self/blob/6a493566dcd518f5e043f568b49682a92ceebf00/vm/src/unix/os/os_unix.cpp#L40

However, this causes issues on modern Linux distributions, which mount `/dev` as `noexec`. As far as I'm aware, at least Debian and Gentoo do this. On all systems in use today we should be able to use `MAP_ANONYMOUS` which accomplishes the same thing.

**Comment by kyle-github** [comment]
Huh.  TIL why I see that code sometimes in dusty decks.   Thanks for that tip!

**Comment by russellallen** [comment]
Well that explains that....

Anyway, this seems to fix, and the resultant VM works on the systems I've checked on: https://github.com/russellallen/self/commit/9f41806d3b6bb27df7433fab632ccb756fb87748

Thanks!
