### ISSUE TITLE
missing programmingExamples.self in Clean.snap, readme for the Linux distribution

### ISSUE THREAD

**Issue by faried** [russellallen/self#44]
The [handbook](http://handbook.selflanguage.org/4.5/howtoprg.html) has a section using `anExampleObject`, but it's not present in the shipped Clean.snap for the 4.5 release.

It's been a long time since I tried Self, and I'd forgotten that to launch it I needed to do `./Self -s Clean.snap`.  I kept trying `./Self Clean.snap` and wondering why it didn't work.  A small readme with the Linux distribution might be helpful.

**Comment by russellallen** [comment]
Hi Fareid,

> On 3 Mar 2015, at 6:24 am, Faried Nawaz <notifications@github.com> wrote:
> 
> The handbook <http://handbook.selflanguage.org/4.5/howtoprg.html> has a section using anExampleObject, but it's not present in the shipped Clean.snap for the 4.5 release.
> 
anExampleObject is in the file objects/misc/programmingExamples.self

You can file it in using:

 ‘path/to/programmingExamples.self’ runScript

I’ve updated the standard build script, so when we issue Self 4.6 it will be included. I’ll also add a note in the handbook so people know where to load it from it they don’t have it.
> It's been a long time since I tried Self, and I'd forgotten that to launch it I needed to do ./Self -s Clean.snap. I kept trying ./Self Clean.snap and wondering why it didn't work. A small readme with the Linux distribution might be helpful.
> 

Yeah, that info is buried in the handbook in the list of startup options. You are right - we need a chapter covering downloading, running etc for Linux and Mac.

I’ll see what i can do.

Please keep on telling us your issues! Russell

**Comment by russellallen** [comment]
fixed in latest commit
