### ISSUE TITLE
Handbook typos

### ISSUE THREAD

**Issue by davidgraham** [russellallen/self#54]
Hello,
I've been working through the Self handbook that's posted on selflanguage.org, and think I've found a couple typos that are important:

~~1. On the langref page, near the top, under the **Code** section.  The code sample is rendered as 
`1 to: 5 \* i By: 2 \* j Do: [\|:k \| k print ]`
I'm new, but I don't believe the \'s are valid?~~ Sorry, just noticed that was fixed in source.

2. On the morphic page, about halfway down, 
*To set the module for the new morphs home slot, invoke “Show annotation” on the ovalMorph slot in the globals object, type “ovalMorph” in the module field, and accept the change (Figure 11).*
Should it be *ovalModule* instead of *ovalMorph* as show in the pictures?

**Comment by russellallen** [comment]
Fixed, thanks
