### ISSUE TITLE
Building a Self-inspired JavaScript prototypal system

### ISSUE THREAD

**Issue by backspaces** [russellallen/self#57]
This is just a request for information: JavaScript supports prototypal inheritance and techniques, indeed JS was built with Self in mind.

What I'm looking for is how to transfer "the magic" Self has of friction-free, very fluid development.

The system is an Agent Based Modeling framework, modeled after NetLogo. Here's our work so far:
    http://agentscript.org
.. and we're upgrading from its current CoffeeScript form to the latest JS: e6, so moving to prototypal methods would be reasonable.

But I'm not sure how to properly use prototypal methodologies to achieve Self's breakthrough in direct usage .. "thinking in Self".

Any pointers?

**Comment by russellallen** [comment]
Javascript's inheritance is a bit different to Self's, but some people have tried to implement the Self UI in javascript. Dan Ingall's Lively Kernel might be a place to start. I'd recommend playing with Self a bit to get the feel for it.

In any case, this is probably a better discussion for the Self mailing list - https://groups.yahoo.com/neo/groups/self-interest/info

**Comment by backspaces** [comment]
Thanks! I saw a mail list on the site but it wasn't this one.  I'll join and chat!
