### ISSUE TITLE
Inner methods are no longer supported?

### ISSUE THREAD

**Issue by dram** [russellallen/self#67]
When trying the first example in Language Reference in handbook, I encountered an "inner methods" error.

Code to run:

```
( | slot1. slot2 | 'here is some code' printLine )
```

Error reported:

```
inner methods are no longer supported, slot-list within a sub expression is not legal.
```

Is LangRef needed to be updated?

BTW, this error message seems to be a bit obscure, what is *inner method*?

**Comment by dram** [comment]
I found that no error will be triggered if I put code into a file and load it by `Self -f`.

**Comment by russellallen** [comment]
When you are in an evaluator on an object in the UI, you are creating a fragment of code which it runs by putting the fragment in a method. If you are defining a method, then you are defining that method in another method (an 'inner method') which isn't currently allowed. If you want to create a method, you will need to create it in an object, e.g.
(| value = (|slot1. slot2| 'here is some code' printLine ) |)

This creates an object with a single method 'value'.

**Comment by dram** [comment]
Nice, get it.
