### ISSUE TITLE
Self doesn't find arialBold (4.4)

### ISSUE THREAD

**Issue by manveru** [russellallen/self#7]
I cannot see any text in the UI, here's the output from a Demo run on Arch Linux.

    chi ~ % Self -s /usr/share/self/0/Demo-4.4.snap
    for I386:  LogVMMessages = true
    for I386:  PrintScriptName  = true
    for I386:  Inline = true
    for I386:  SICDeferUncommonBranches = false (not implemented)
    for I386:  SICReplaceOnStack = false (not implemented)
    for I386:  SaveOutgoingArgumentsOfPatchedFrames = true
    
      Welcome to the Self system!  (Version 4.4)
    
    
    Copyright 1992-2009 AUTHORS, Sun Microsystems, Inc. and Stanford University.
    See the LICENSE file for license information.
    
    Type _Credits for full credits.
    
    VM version: 4.1.13
    
    Adjusting VM for better UI2 performance:
      _MaxPICSize: 25
      _Flush
    "Self 1" unknown font: arialBold
    ^C
      ----------------Interrupt-----------------
      Waiting:
        <0> waiting process: perProcessGlobals prompt mainInputLoop             
      ------------------------------------------
      Select a process (or q to quit scheduler): q
      Scheduler shut down.
      ------------------------------------------
    VM# 
    chi ~ % locate arial
    /usr/share/fonts/TTF/arial.ttf
    /usr/share/fonts/TTF/arialbd.ttf
    /usr/share/fonts/TTF/arialbi.ttf
    /usr/share/fonts/TTF/ariali.ttf

**Comment by russellallen** [comment]
Cleanup - open new issue if this reoccurs.
