### ISSUE TITLE
Where's the debugger?

### ISSUE THREAD

**Issue by dram** [russellallen/self#84]
[Handbook](http://handbook.selflanguage.org/4.5/howtoprg.html#debugger) says that a debugger will be opened when an error is triggered, but I can not find it, only an error message is displayed, see screenshot for more detail.

Did I do anything wrong?

![screenshot](https://cloud.githubusercontent.com/assets/517130/19417347/f4a6026e-93dc-11e6-87d3-5b2756ffbb03.png)

**Comment by doublec** [comment]
Behaviour seems to have changed. Looking at an older checkout of the source tree doing the same thing (except using 'foo') gives:

![self_debugger](https://cloud.githubusercontent.com/assets/16599/19420919/2ad3c568-9452-11e6-8143-ae7ac0db913f.png)

I notice in your error message that "evniromentAt" is spelt wrong. Perhaps that's the cause?

**Comment by dram** [comment]
This typo is intentional, which is an example in handbook to trigger the debugger.

**Comment by doublec** [comment]
I'm bisecting now - should have a result soon.

**Comment by doublec** [comment]
Change in behaviour was introduced in commit 6ff3acf3144cf615fa9509af32aa0895a7cdd3c0

**Comment by russellallen** [comment]
Mea culpa - my commit. I'll have a look and see how I managed to do it!

**Comment by russellallen** [comment]
OK, I think that fixed it. For reasons unknown at one point a call to 'isAlive' changed to 'isActive'. Reopen if its still broken for you.

**Comment by doublec** [comment]
That fixed it for me, thanks for the quick fix!
