### ISSUE TITLE
How to read file by line and detect EOF?

### ISSUE THREAD

**Issue by dram** [russellallen/self#92]
I find that `traits abstractFile readLine` will raise an error when EOF is encountered. So how can I detect EOF while reading lines?

**Comment by dram** [comment]
It may be related to issue #89.

**Comment by dram** [comment]
Continue to investigate into this problem, I found conflict between comment and behavior of `positionableStream readingMixin readMin:Max:IfFail:`, comment says:

> may return less than min if it reaches the end

But actual behavior is that if reading more characters than file contains, an `EOF...` error is raised, instead of *return less...*.

**Comment by russellallen** [comment]
OK so I think your changes fix this.
